# Generated by Django 4.2.27 on 2025-12-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_telegramprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
    ]
