# Generated by Django 4.2.27 on 2025-12-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='binding_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
